- name: Create Diun app folder
  file: 
    path: /app/diun/data
    state: directory
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
- name: Apply Diun config
  template:
    src: diun.yml.j2
    dest: /app/diun/diun.yml
- name: Copy Nextcloud Nginx config
  copy:
    src: custom-images.yml
    dest: /app/diun/custom-images.yml
- name: Create Duin container (rootfull)
  containers.podman.podman_container:
    name: diun
    image: docker.io/crazymax/diun:latest
    volume:
      - "/app/diun/data:/data:z"
      - "/app/diun/diun.yml:/diun.yml:z"
      - "/app/diun/custom-images.yml:/custom-images.yml:z"
    env:
      TZ: "Europe/Amsterdam"
      LOG_LEVEL: "info"
      LOG_JSON: false
    label:
      diun.enable: true
      diun.watch_repo: true