- hosts: foto-server
  become: true
  vars_files:
    - vars/secrets.yml
  vars:
    samba_shares_root: /srv/shares
    samba_netbios_name: FOTO-SERVER
    samba_workgroup: THUIS
    samba_users:
      - name: "michael"
        password: "{{ SAMBA_USER_PASSWORD }}"
    samba_shares:
      - name: photos
        comment: My photo share
        write_list: "+michael"
  roles:
    - base
    - podman
    - bertvv.samba 
  tasks:
    - name: Create Photoprism storage folder
      file:
        path: /app/photoprism/storage
        state: directory
    - name: Pull latest Photoprism image
      containers.podman.podman_image:
        name: docker.io/photoprism/photoprism:20220121
    - name: Create Photoprism container
      containers.podman.podman_container:
        name: photoprism
        image: docker.io/photoprism/photoprism:20220121
        volume:
          - /app/photoprism/storage:/photoprism/storage
          - /srv/shares/photos:/photoprism/originals
        ports:
          - 80:2342
        env:
          PHOTOPRISM_DATABASE_DRIVER: "mysql"
          PHOTOPRISM_DATABASE_SERVER: "{{ groups['db'][0] }}:3306"
          PHOTOPRISM_DATABASE_NAME: "photoprism"
          PHOTOPRISM_DATABASE_USER: "photoprism"
          PHOTOPRISM_DATABASE_PASSWORD: "{{ PHOTOPRISM_MYSQL_PASSWORD_SECRET }}"
          PHOTOPRISM_ADMIN_PASSWORD: "{{ PHOTOPRISM_PASSWORD_SECRET }}"
          PHOTOPRISM_UPLOAD_NSFW: "true"
          PHOTOPRISM_DETECT_NSFW: "false"

- hosts: db
  become: true
  remote_user: root
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Install bottle python package
      package:
        name: python3-pip
    - name: Install bottle python package
      pip:
        name: PyMySQL
    - name: Create database
      community.mysql.mysql_db:
        config_file: /etc/mysql/my.cnf
        login_user: "{{ MYSQL_USER_SECRET }}"
        login_password: "{{ MYSQL_PASSWORD_SECRET }}"
        name: photoprism
        state: present
    - name: Create database user
      community.mysql.mysql_user:
        config_file: /etc/mysql/my.cnf
        login_user: "{{ MYSQL_USER_SECRET }}"
        login_password: "{{ MYSQL_PASSWORD_SECRET }}"
        name: photoprism
        state: present
        password: "{{ PHOTOPRISM_MYSQL_PASSWORD_SECRET }}"
        host: "{{ groups['foto-server'][0] }}"
        priv: 'photoprism.*:ALL'

