- hosts: foto-server
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
    - base
    - podman
  tasks:
    - name: Create Photoprism storage folder
      file:
        path: /app/photoprism/storage
        state: directory
    - name: Create fotoos storage folder
      file:
        path: /mnt/fotoos
        state: directory
    - name: Mount NFS fotoos share
      ansible.posix.mount:
        src: "192.168.1.100:/WD-Reds/fotoos"
        path: /mnt/fotoos
        fstype: nfs
        opts: "rw,sync"
        state: mounted
    - name: Pull latest Photoprism image
      containers.podman.podman_image:
        name: docker.io/photoprism/photoprism:220901-bookworm
    - name: Create Photoprism container
      containers.podman.podman_container:
        name: photoprism
        image: docker.io/photoprism/photoprism:220901-bookworm
        volume:
          - /app/photoprism/storage:/photoprism/storage
          - /srv/shares/photos:/photoprism/originals
        ports:
          - 80:2342
        env:
          PHOTOPRISM_DATABASE_DRIVER: "mysql"
          PHOTOPRISM_DATABASE_SERVER: "{{ groups['db'][0] }}:3306"
          PHOTOPRISM_DATABASE_NAME: "photoprism"
          PHOTOPRISM_DATABASE_USER: "photoprism"
          PHOTOPRISM_DATABASE_PASSWORD: "{{ PHOTOPRISM_MYSQL_PASSWORD_SECRET }}"
          PHOTOPRISM_ADMIN_PASSWORD: "{{ PHOTOPRISM_PASSWORD_SECRET }}"
          PHOTOPRISM_UPLOAD_NSFW: "true"
          PHOTOPRISM_DETECT_NSFW: "false"

- hosts: db
  become: true
  remote_user: root
  vars_files:
    - vars/secrets.yml
  tasks:
    - name: Install bottle python package
      package:
        name: python3-pip
    - name: Install bottle python package
      pip:
        name: PyMySQL
    - name: Create database
      community.mysql.mysql_db:
        config_file: /etc/mysql/my.cnf
        login_user: "{{ MYSQL_USER_SECRET }}"
        login_password: "{{ MYSQL_PASSWORD_SECRET }}"
        name: photoprism
        state: present
    - name: Create database user
      community.mysql.mysql_user:
        config_file: /etc/mysql/my.cnf
        login_user: "{{ MYSQL_USER_SECRET }}"
        login_password: "{{ MYSQL_PASSWORD_SECRET }}"
        name: photoprism
        state: present
        password: "{{ PHOTOPRISM_MYSQL_PASSWORD_SECRET }}"
        host: "{{ groups['foto-server'][0] }}"
        priv: 'photoprism.*:ALL'

