- hosts: nextcloud
  become: true
  vars_files:
    - vars/secrets.yml
  vars:
    TUNNEL_NAME: nxtcld20
    TUNNEL_SERVICES:
      - { port: 8080, hostname: "{{ NEXTCLOUD_HOST }}" }
  roles:
    - base
    - podman
    - nextcloud
    - diun
    - cloudflare-tunnel