- hosts: proxmox
  become: true
  vars_files:
    - vars/secrets.yml
  vars:
    samba_shares_root: /srv/shares
    samba_netbios_name: PROXMOX
    samba_server_string: ''
    samba_workgroup: THUIS
    # samba_global_include: global-include.conf

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000
    samba_log_level: '3 passdb:5 auth:10 winbind:2 '
    samba_users:
      - name: "michael"
        password: "{{ SAMBA_USER_PASSWORD }}"
    samba_shares:
      - name: drives
        comment: Media drives
        write_list: "+michael"
        valid_users: "+michael"
  roles:
    - base
    - bertvv.samba 