- hosts: proxmox
  become: true
  vars_files:
    - vars/secrets.yml
  vars:
    samba_shares_root: /srv/shares
    samba_netbios_name: PROXMOX
    samba_workgroup: THUIS

    samba_users:
      - name: "michael"
        password: "{{ SAMBA_USER_PASSWORD }}"
    samba_shares:
      - name: drives
        comment: Media drives
        write_list: "+michael"
        valid_users: "+michael"
  roles:
    - base
    - bertvv.samba 