- hosts: torrentbox
  become: true
  vars_files:
    - vars/secrets.yml
  roles:
    - base
    - podman
    - vpn
    - torrentbox
    - geerlingguy.nfs
  vars:
    nfs_exports:
      - "/mnt/1tb *(ro) 192.168.1.2(rw)"
  tasks:
    - name: Open NFS ports
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
      loop:
        - nfs
        - mountd
        - rpc-bind
