- name: Create mqtt config folder
  become: true
  file:
    path: /var/home/core/mqtt
    state: directory
    owner: "1883"
    group: "1883"

- name: Copy mosquitto config
  become: true
  copy:
    src: mosquitto.conf
    dest: /var/home/core/mqtt/mosquitto.conf
    owner: "1883"
    group: "1883"

- name: mosquitto auth
  become: true
  template:
    src: auth.txt.j2
    dest: /var/home/core/mqtt/auth.txt

- name: Deploy Quadlet container file
  become: true
  template:
    src: mqtt.container.j2
    dest: /etc/containers/systemd/mqtt.container
  notify: Restart mqtt

- name: Enable and start mqtt systemd unit
  become: true
  systemd:
    daemon_reload: true
    name: mqtt
    state: started
    enabled: true
