- name: Create home-assistant config folder
  become: true
  file:
    path: /app/home-assistant/
    state: directory
    owner: "1000"
    group: "1000"
- name: Open firewall ports
  become: true
  ansible.posix.firewalld:
    port: "8123/tcp"
    state: enabled
- name: Pull latest image
  become: true
  containers.podman.podman_image:
    name: homeassistant/home-assistant:latest
- name: Create home-assistant container
  become: true
  containers.podman.podman_container:
    name: home-assistant
    image: homeassistant/home-assistant:latest
    restart_policy: always
    env:
      TZ: Europe/Amsterdam
    recreate: yes
    privileged: true
    volume:
      - /app/home-assistant/config:/config:z
    ports:
      - "8123:8123"