- name: Create Nextcloud app folder
  file:
    path: /app/nextcloud/config
    state: directory
    # 82 is www-data user id from the nextcloud container
    owner: "82"
    group: "82"
- name: Start Redis container
  containers.podman.podman_container:
    image: redis:6.2.6-alpine
    name: redis
    command: "redis-server --requirepass {{ REDIS_PASSWORD_SECRET }}"
    recreate: true
    network:
      - nextcloud
- name: Start Nextcloud container
  containers.podman.podman_container:
    name: nextcloud-app
    recreate: true
    image: nextcloud:23.0.0-fpm-alpine
    volume:
      - "{{ NEXTCLOUD_VOLUME_NAME }}:/var/www/html"
      - /app/nextcloud/config:/var/www/html/config:z 
    env:
      MYSQL_PASSWORD: "{{ NEXTCLOUD_MYSQL_PASSWORD_SECRET }}"
      MYSQL_DATABASE: "{{ NEXTCLOUD_MYSQL_DATABASE_NAME }}"
      MYSQL_USER: "{{ NEXTCLOUD_MYSQL_DATABASE_USER }}"
      MYSQL_HOST: "{{ NEXTCLOUD_MYSQL_DATABASE_HOST }}"
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: "{{ REDIS_PASSWORD_SECRET }}"
    network: 
      - "{{ NEXTCLOUD_NETWORK_NAME }}"
- name: Start Nextcloud Cron container
  containers.podman.podman_container:
    name: nextcloud-cron
    recreate: true
    entrypoint: /cron.sh
    image: nextcloud:23.0.0-fpm-alpine
    volume:
      - "{{ NEXTCLOUD_VOLUME_NAME }}:/var/www/html"
      - /app/nextcloud/config:/var/www/html/config:z
    env:
      MYSQL_PASSWORD: "{{ NEXTCLOUD_MYSQL_PASSWORD_SECRET }}"
      MYSQL_DATABASE: "{{ NEXTCLOUD_MYSQL_DATABASE_NAME }}"
      MYSQL_USER: "{{ NEXTCLOUD_MYSQL_DATABASE_USER }}"
      MYSQL_HOST: "{{ NEXTCLOUD_MYSQL_DATABASE_HOST }}"
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: "{{ REDIS_PASSWORD_SECRET }}"
    network:
      - nextcloud
- name: Copy Nextcloud Nginx config
  copy:
    src: nginx.conf
    dest: /app/nextcloud/nginx.conf
- name: Start Nextcloud Nginx web
  containers.podman.podman_container:
    name: nextcloud-web
    image: nginx:alpine
    recreate: true
    volume:
      - /app/nextcloud/nginx.conf:/etc/nginx/nginx.conf:z
      - "{{ NEXTCLOUD_VOLUME_NAME }}:/var/www/html:ro"
    network: "{{ NEXTCLOUD_NEXTCLOUD_NAME }}"
- name: Reverse proxy config
  copy:
    src: traefik-config.toml
    dest: /app/traefik/conf.d/nextcloud.toml

