- name: Install podman
  package:
    name: podman
    state: latest
- name: Install runc
  # https://github.com/containers/podman/issues/8227
  package:
    name: runc
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: Create networks
  containers.podman.podman_network:
    name: "{{ item }}"
  loop: "{{ PODMAN_NETWORKS }}"
  when: PODMAN_NETWORKS is defined

- name: Create volumes
  containers.podman.podman_network:
    name: "{{ item }}"
  loop: "{{ PODMAN_VOLUMES }}"
  when: PODMAN_VOLUMES is defined