- name: Create torrent config folder
  file:
    path: /app/rutorrent/config
    state: directory
    owner: "1000"
    group: "1000"
- name: Open firewall ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    state: enabled
  loop:
    - 80/tcp
    - 5000/tcp
    - 51413/tcp
    - 6881/udp
- name: Create rutorrent container
  containers.podman.podman_container:
    name: rutorrent
    image: linuxserver/rutorrent
    recreate: yes
    volume:
      - /app/rutorrent/config:/config:z
      - /mnt/1tb/Downloads:/downloads
    ports:
      - 80:80
      - 5000:5000
      - 51413:51413
      - 6881:6881/udp
    env:
      PUID: "1000"
      PGID: "1000" 