- name: Create Mariadb volume
  containers.podman.podman_volume:
    name: mariadb
    state: present
- name: Start Mariadb container
  containers.podman.podman_container:
    name: mariadb
    recreate: true
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volume:
      - mariadb:/var/lib/mysql
    env:
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD_SECRET }}"
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_PASSWORD_SECRET }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE_NAME }}"
      MYSQL_USER: "{{ MYSQL_DATABASE_USER }}"
    network: 
      - "{{ PODMAN_NETWORKS }}"