- name: eclipse-mosquitto
- name: photoprism/photoprism
- name: nodered/node-red
- name: linuxserver/rutorrent
- name: homeassistant/raspberrypi3-homeassistant
- name: koenkk/zigbee2mqtt
- name: nextcloud
- name: redis
- name: traefik
- name: crazymax/diun