- name: Install firewalld
  package:
    name: firewalld
    state: latest
  when: ansible_distribution == 'Fedora'
- name: Enable firewalld
  systemd:
    state: started
    name: firewalld
    enabled: yes
  when: ansible_distribution == 'Fedora'
- name: Install favorite pacakges
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - vim
    - htop
    - iotop
    - tmux

- name: NFS utility present redhat-like
  ansible.builtin.yum:
    name:
      - nfs-utils
      - nfs4-acl-tools
    state: present
  when: ansible_os_family == 'RedHat'

- name: NFS utility present debian-like
  ansible.builtin.apt:
    name:
      - nfs-common
      - nfs4-acl-tools
    state: present
  when: ansible_os_family == 'Debian'