- name: Create torrent config folder
  file:
    path: /app/node-red/
    state: directory
    owner: "1000"
    group: "1000"
- name: Open firewall ports
  ansible.posix.firewalld:
    port: "1880/tcp"
    state: enabled
- name: Create node-red container
  containers.podman.podman_container:
    name: node-red
    image: nodered/node-red:2.1.4-1
    user: 1000
    recreate: yes
    volume:
      - /app/node-red:/data:z
    ports:
      - 1880:1880